export default {
  // normal
  PING: "PING",
  // response sub type
  ERROR: "ERROR",
  PERSONAL: "PERSONAL", // 取得個人資訊
  ROOM_USERS: "PERSONAL",
  // room
  JOIN_ROOM: "JOIN_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",
  // message
  MESSAGE: "MESSAGE",
  SEND_MESSAGE: "SEND_MESSAGE",
  PUSH_MESSAGE: "PUSH_MESSAGE",
  RESPONSE: "RESPONSE",
  /*** webRtc ***/
  WEB_RTC: "WEB_RTC",
  //offer
  SEND_OFFER: "SEND_OFFER",
  RECEIVE_OFFER: "RECEIVE_OFFER",
  // answer
  SEND_ANSWER: "SEND_ANSWER",
  RECEIVE_ANSWER: "RECEIVE_ANSWER",
  // candidate
  SEND_CANDIDATE: "SEND_CANDIDATE",
  RECEIVE_CANDIDATE: "RECEIVE_CANDIDATE",
}