export default {
  // normal
  PING: "PING",
  // message
  MESSAGE: "MESSAGE",
  SEND_MESSAGE: "SEND_MESSAGE",
  PUSH_MESSAGE: "PUSH_MESSAGE",
  // room
  ROOM_JOIN: "ROOM_JOIN",
  ROOM_LEAVE: "ROOM_LEAVE",
  // system
  SYSTEM_DISCONNECT: "SYSTEM_DISCONNECT",
  // response
  RESPONSE: "RESPONSE",
  RESPONSE_ERROR: "RESPONSE_ERROR",
  RESPONSE_PERSONAL: "RESPONSE_PERSONAL", // 取得個人資訊
  RESPONSE_ROOM_USERS: "RESPONSE_ROOM_USERS",
  /*** webRtc ***/
  WEB_RTC: "WEB_RTC",
  WEB_RTC_OPENED: "WEB_RTC_OPENED",
  //offer
  WEB_RTC_SEND_OFFER: "WEB_RTC_SEND_OFFER",
  WEB_RTC_RECEIVE_OFFER: "WEB_RTC_RECEIVE_OFFER",
  // answer
  WEB_RTC_SEND_ANSWER: "SEND_ANSWER",
  WEB_RTC_RECEIVE_ANSWER: "WEB_RTC_RECEIVE_ANSWER",
  // candidate
  WEB_RTC_SEND_CANDIDATE: "SEND_CANDIDATE",
  WEB_RTC_RECEIVE_CANDIDATE: "WEB_RTC_RECEIVE_CANDIDATE",
}