export default {
  // normal
  PING: "PING",
  INFO: "INFO",
  // room
  JOIN_ROOM: "JOIN_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",
  // message
  SEND_MESSAGE: "SEND_MESSAGE",
  PUSH_MESSAGE: "PUSH_MESSAGE",
  RESPONSE: "RESPONSE",
  MESSAGE: "MESSAGE",
  // webRtc
  //offer
  SEND_OFFER: "SEND_OFFER",
  RECEIVE_OFFER: "RECEIVE_OFFER",
  // answer
  SEND_ANSWER: "SEND_ANSWER",
  RECEIVE_ANSWER: "RECEIVE_ANSWER",
  // candidate
  SEND_CANDIDATE: "SEND_CANDIDATE",
  RECEIVE_CANDIDATE: "RECEIVE_CANDIDATE",
}